language: python
matrix:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: "3.7"
      dist: xenial
      before_install: pip3 install --upgrade pip
#    - name: "Python 3.7 on macOS"
#      os: osx
#      osx_image: xcode10.2
#      language: shell
#      before_install: pip3 install --upgrade pip
#    - name: "Python 3.7 on Windows"
#      os: windows
#      language: shell
#      before_install:
#        - choco install python
#        - python -m pip install --upgrade pip
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --user codecov
  - pip3 install -r requirements.txt
script:
  - python -m pytest
after_success:
  - codecov